sudo: required
language: java
jdk:
- openjdk11
before_install:
- openssl aes-256-cbc -K $encrypted_5e203709a340_key -iv $encrypted_5e203709a340_iv
  -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
script:
- ./mvnw clean install
- |
  set -e
  if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
     echo "Importing GPG key into keyring"
     gpg --fast-import travis/codesigning.asc
     ./mvnw versions:set -DnewVersion="$COMMIT_SHORT"

     echo "Running release"
     ./mvnw --settings travis/settings.xml deploy -Prelease -DskipTests=true
  fi
notifications:
  slack:
    secure: NUMs/SN5ZsR/IVcwUiOPJXrvHbSUmt1fgr2Qw0ULFqhJy+OLsdBdQnCX5xpXfULKvaVw32i5njUWY4kbyOdjDIf7plQBt7zJoSYK9LUQTQHD+0YArreY2rFddnsA+F1ruNZd45t/FSA5nSEP/alVuwE8V6/Q2FFskhepEwXS2CWx6W3ww4DnSHHuRwydzVm0rB9t1b275Y/Nh1r/EBdUOyFcaV5ttAZoOgMBoeXD/aHjATXTqJJIw8JnmTruX3uFTvvu4Ti4OiqyexqBopvsD63wMCZ7gAB8NoJmP1YTZI4afA/RaPlqCo8YrHjeC0qy7iDxdI7QX6a0+bEL7naw/Sj0hZN4sSQevfvDd/JT90rtcK8yPb9WWUXkY2ByKE7Ls31uvbbWUeZZZwOdDgToYAWaH6RntX0ayTPNpvZdU05Zh0SGOaTWLxgp+uYfitB/G4o0V7b9f/boNhBBuizCSwn8KvYYE5RznxNk6vh86+JQnlrT+/S2Lthe3lIkYPtaGf4z4TxarzioCblchQqJChr7Ki8CzntwvHPpXKsmy9YDkV77mjvnWG5zDbafyUg17W2fC6MlXfMLhuHhJwXje77F5C4GwuhvttY+3QWaLx+r4qlE94gXW4on9JYXaIxeHyCunYL6+V4vGol4Wd2QIvB+H82FYfAWe+Mk/iO2Tvk=
env:
  global:
  - OSSRH_JIRA_USERNAME=navikt
  - secure: Z2eXCCcnUXGbHICA4PEDcI+/3U/kmV9nQZn+/ug847KgovlxetSIEXulTFplCtugPaohUaeVE06oRI9mFG8zh+vqXfdhayTTG4yu6CZVyeQN03iEsd5hvr2NOdD8Xr/t6289K7zoB7nybB314xwrX6H8o89/ijSxJqNwnJP+t/yARhPeSC7jfag0kLBc1FYsiLGGtqvMqIZvQDFnSnM63XO8aieCOrv2f9o7sbb6L/9KQJ9nNBDrIP1RKd8oRaBdRsvYcIc1bmtXwTQA+P7yQ0pWv4zTDsGTsmeSnWRVNUTmFx+v2X5nOG3bWL6vXUaW1v7flyTFtQSTXGNsKmhMMaKUi6makpHQPCmlLDUHUPaGG/ZCzvUEL3oHod2znh0kmfK/ZUm8TMsSCe6884seNHgBM40bnFi9yFnc0QOmoA5t+UD8/xFryLPZeJQRvQ7qDf8U+C9I1SSVu8Ef9rELt3XWWWcdSOgY+xEKpom8tC6SdnczCG1Ct1CrlFjPmQSxTfLh7qdLDK2WWkM8i7AybVF3yhG4s0HSXMj9TjsnxLpMrI+B5yA/c6T5Hm4x8LsyIMQceS61tf/FymbjxulR6NIHeQOisBNv/Xuziog6GBOBktRXTu6GlHiEHbegRsCfkPIwK70Ro4gFks8tsuWZF5bYYWGfhiGcJcMr2hM2lck=
  - GPG_KEY_NAME=navikt
  - secure: kLhOCEbjs4EmRtcBGcqKpM1wPWzIJgII7s9h6lJdFwB2jjiRXQi83IbbylD1dOtv4zWZ4VXLh4QgiR50NZ96MduszImGaYIJZ//1m41Le9DU14+QY63b2IEhMdFzsfg1yV6UKm8A2MggiPIjhfr45mgjTr0lAF8buYQdbMLPVE8d9GW9UErhBft3oJUBWctRkR3730gFYWjTShzEYGU297WxmacuM8y+k9he/V6GcuRo/wEBFx3iKf/oRehtqs/MNiykBUL+rGNHUXG00b37rnczcSgdb76Pfu2VOxgI0xXqwK8zEaKmZSrLyftWlYTV6WYlxEG+WXs9OioYOtdSRUgEpuaWq7rkPliKcDhHlSKH+4eNpuhoWjllvOCaDapouCOifhAZVq4G2FCJJjHIHKgQmYj3DXINJrJpZ4VUDSEu8xTcZ4C1GDPh9AM4XubrETE/fBp8Xyb52jRn1xRzMPFUs4Oq2yUvzAF6djUWlwQLMCPC569qCtosAU7ODy7uGTLI9ueTSGvB8Yn48shzOn750Cxk63hbq7l9CsXDOk9RvxDTtLio0rq1wFpJkfdhvdGSs2CdU64Sm0UqSUooP9KGztbteO3gFq8LiyhNFqtcg0lnRu6A/vrbvjOUeWSzWb9BdYEMZD3Cmj601mdAMKaw77DygdUZ+AEpa9b4+NM=
  - secure: dlmkPdh0bmwaIUw9lysee4MTWxh6+/40BQQrMy0ZS2+PPuWtLkmavwMIT3vPdRnsOcNp4vnDmsSohhFEci0Y32+rtxHh0w8N9fB25ac/ERBeXOUM3i2NsRef6JFgg2sASp7EJ7YnWQZ8V1/Lp7diiaXCPa7QkxR532e9eZ6168Geb+aag6fUt6s/GolphZ+actnQKkiQk44YM7dLPU50g8si/RlVgoLqPqL2ujaWiV36jBqAv4EfLLE9t48+7kLrmnYOWaaoeauilwze/QYbNoKJGuGmYy9i2K/edHXsRHsKYm2SqSnqtpSY2WPsfXGbo8fl2fhwC/4Nn4xgcTh9CmtxWh/FqaB/c+99yWa2JOYQxi5KV4VCzdMl4WyrKL/e2v3Sh8EBQel+W4Re1p4Njy0ad0gW1AXPD/KtHvj/vID+xhRY5+i0EAphgxzCOyuEza1VPVQr1qPRbQ0TX1jQGyqYDxXRczYK4wbfYhrEpv8653P8f03UDbRLu+8DfSXzVWu6FnAyYdizmQzbUjS9pxzjQfp8I32WE+FbBGZV97yn0esaUyQ9uLTvMSJo/fm7bVj2/IKHLpfsm3GjmnT54msMY3akqfpcs+CKg/zUwUtkejx0sV2Jws0WSyHiG1z1kc7E8ZCYNCXfBycpgv3rXW5e5Pl/l/GSmVbCIXvip78=
